import =[
"~/.config/alacritty/themes/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10 
opacity = 0.8
blur = true
decorations = "buttonless"

[font]
size = 24

[font.normal]
family = "MesloLGS Nerd Font Mono"

