import =[
"~/.config/alacritty/themes/roseprime.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15 
opacity = 0.95
blur = true
decorations = "buttonless"

[font]
size = 24

[font.normal]
family = "MesloLGS Nerd Font Mono" 
