[env]
TERM="xterm-256color"

[colors.primary]
# background = "#181818" # For Grub
background = "#3F3F3F"   # For Zenburn

[window]
padding.x = 12
padding.y = 12 
decorations = "none" 

[mouse]
hide_when_typing = true

# [cursor]
# style.blinking = "On"

[font]
size = 31

[font.normal]
family = "Iosevka Nerd Font Mono"
