[env]
TERM="xterm-256color"

[colors.primary]
background = '#0D0C00'

[window]
padding.x = 15
padding.y = 15 
decorations = "none" 

[font]
size = 24

[font.normal]
family = "FiraCode Nerd Font Mono" 
