import =[
  "~/.config/alacritty/themes/themes/github_dark_default.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10 
opacity = 0.8
blur = true
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "Hurmit Nerd Font"
size = 24 
