[env]
TERM = "xterm-256color"

[colors.primary]
background = '#0C0B00'

[window]
padding.x = 15
padding.y = 15 
decorations = "none" # or 'buttonless'

[font]
size = 24

[font.normal]
# family = "MesloLGS Nerd Font Mono" 
family = "Hack Nerd Font Mono" 
