import =[
"~/.config/alacritty/themes/themes/roseprime.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12 
# opacity = 0.8
# blur = true
decorations = "buttonless"

[font]
size = 24

[font.normal]
family = "MesloLGS Nerd Font Mono"


