import =[
  "~/.config/alacritty/themes/themes/bamboo.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "Operator-Caska"

size = 20 
