[env]
TERM="xterm-256color"

[colors.primary]
background = '#0E0E0E'

[window]
padding.x = 12
padding.y = 12 
decorations = "none" 

[mouse]
hide_when_typing = true

[font]
size = 31

[font.normal]
family = "Iosevka Nerd Font Mono"
