import =[
  "~/.config/alacritty/themes/themes/one_dark.toml"
]

[env]
TERM = "xterm-256color"


[window]
padding.x = 10
padding.y = 10 

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"

size = 22 
