import =[
  "~/.config/alacritty/themes/themes/poimandres.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10 
# opacity = 0.8
# blur = true
decorations = "buttonless"
option_as_alt = "Both"

[font]
size = 22

[font.normal]
family = "FiraCode Nerd Font"

